### ISSUE TITLE
How to download `data_splits_patients.pickle` or `data_splits_pdo_fib.pickle`

### ISSUE THREAD

**Issue by noboru-isobe** [lazaratan/meta-flow-matching#1]
I hope this message finds you well. 
I have encountered an issue while trying to run the biological experiments.

When executing the command `python train.py experiment=trellis_mfm.yaml,` I receive an error indicating that the file `data_splits_patients.pickle` is missing. I've followed the instructions in the README, including running the `trellis_data.ipynb` notebook for data preprocessing. and could download the dataset file `trellis_patients_normalized.npy.`
However, I couldn't find any information on how to obtain or generate this specific pickle file.

Please provide guidance on how to acquire or create the 'data_splits_patients.pickle' file. Is there an additional step I missed?

Thank you for your time and assistance. I look forward to your response.

**Comment by lazaratan** [comment]
To streamline the process of acquiring the relevant files for the biological data, I have uploaded the splits (pickle files) and and respective preprocessed and normalized data (npy files) [here](https://huggingface.co/datasets/lazaratan/meta-flow-matching-organoid-data-preprocessed)

You can also find this link in the updated repo. Note the dataloader was slightly updated to automatically select the correct preprocessed normalized data using the data split hparam, instead of manually making the change as in the previous versions of the code.

Otherwise, if you are using the `trellis_data.ipynb` notebook, cell 27 saves the replicas split (pickle), cell 34 saves the replicas normalized data (npy), cell 42 saves the patients split (pickle), and cell cell 50 saves the patients normalized data (npy).
